blank_issues_enabled: false
contact_links:
  - name: Add new ToDo
    about: made by create_todo.md
    # edit {username} and {repo} for your environment
    url: https://github.com/S-Kawabuchi/MyToDo/issues/new?template=custom.md&projects=S-Kawabuchi%2FTask%2F1&labels=ToDo
